FORMAT: 1A
HOST: http://localhost:4567

# mysql_learn

MySQL勉強会用ウェブAPI

## Message Collection [/messages]

### List All Message [GET]

+ Response 200 (application/json)

        "messages": [
            {
                "id": 1,
                "text": "Ducimus quisquam qui natus magnam quam.",
                "user_id": 273
            },
            {
                "id": 2,
                "text": "Aut dolor ex eos enim iste reiciendis sed.",
                "user_id": 365
            },
            {
                "id": 3,
                "text": "Magnam perspiciatis laboriosam suscipit non repellat minima.",
                "user_id": 18
            }
        ]

### Create a New Message [POST]

新規メッセージを作成します。 JSONオブジェクトにメッセージ本文とユーザーIDが必要です。

+ Request (application/json)

        {
            "question": "Aut dolor ex eos enim iste reiciendis sed.",
            "user": [
                "id": 1
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /messages

    + Body

            {
                "message": "Aut dolor ex eos enim iste reiciendis sed.",
                "user": [
                    "id": 1,
                    "name": "Hory slime"
                ]
            }
            
## One Message [/messages/{id}]
+ Parameter
    + id (required, number, `1`) ... ID of the Message in form of an integer.

### Get One Message [GET]
+ Response 200 (application/json)

        "message": {
            "id": 1,
            "text": "Ducimus quisquam qui natus magnam quam.",
            "user_id": 273
        }

## Users Collection [/users]

### List All Users [GET]
+ Response 200 (application/json)

        "users": [
            {
                "id": 1,
                "name": "Flow Harey"
            },
            {
                "id": 2,
                "text": "Julliane Legrus"
            }
            {
                "id": 3,
                "text": "Paxton Grims"
            }
        ]
        
## One User [/users/{id}]
+ Parameters
    + id (required, number, `1`) ... ID of the User in form of an integer.

### Get One User [GET]
+ Response 200 (application/json)

        "user": {
            "id": 1,
            "name": "Hory slime"
        }
        
## User Messages Collection [/users/{id}/messages]
+ Parameters
    + id (required, number, `1`) ... ID of the User in form of an integer.

### List All User Messages [GET]
+ Response 200 (application/json)

        "messages": [
            {
                "id": 624,
                "text": "Modi autem error ad quia quis nostrum aliquam.",
                "user_id": 1,
                "user": {
                    "id": 1,
                    "name": "Julianne Legros"
                }
            },
            {
                "id": 1259,
                "text": "Reprehenderit qui dolores atque debitis amet dolor quis.",
                "user_id": 1,
                "user": {
                    "id": 1,
                    "name": "Julianne Legros"
                }
            },
            {
                "id": 1448,
                "text": "Cupiditate ratione in enim et non nesciunt eum.",
                "user_id": 1,
                "user": {
                    "id": 1,
                    "name": "Julianne Legros"
                }
            }
        }